#!/bin/bash
echo "Running bump+tag script."

ver_string=$1
if [ "$ver_string" == "" ]
	then
	echo "No tag string supplied."
	exit
fi

if git diff-index --quiet HEAD; then
	echo "No uncommitted changesl proceeding."
else
	echo "There are uncommitted changes."
	exit
fi

#bump agv
#agvtool bump -all
ver_num=`agvtool vers -terse`

#commit
#git commit -am "Commit agv bump to $ver_num"

full_text="Tag for $ver_string ($ver_num)"
#git tag -m "$full_text" $ver_string

#git push
#git push --tags

