#!/bin/bash
ver_string=$1
if [ "$ver_string" == "" ]
	then
	echo "No tag string supplied."
	exit
fi

if git diff-index --quiet; then
	echo "There are uncommitted changes."
	exit
fi

echo "Running bump+tag script."

#should check ver string is non-null
#should check rep has no uncommitted changes

#bump agv
agvtool bump -all
ver_num=`agvtool vers -terse`

#commit
git commit -am "Commit agv bump to $ver_num"

full_text="Tag for $ver_string ($ver_num)"
git tag -m "$full_text" $ver_string

git push
git push --tags

